name: Dart CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  checks:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
      - uses: actions/checkout@v3
      - run: dart pub get
      - run: dart analyze lib test
      - run: dart test
      - run: dart format .
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update formatted files
          file_pattern: "*.dart"
